### ISSUE TITLE
how is "joyent/FreeBSD-12.0-CURRENT-VPC" built?

### ISSUE THREAD

**Issue by trentm** [joyent/freebsd-vpc#5]
https://app.vagrantup.com/joyent/boxes/FreeBSD-12.0-CURRENT-VPC

How is that image built? Sean and Sam didn't know. For example, if (for starters) I wanted to update /home/vagrant/.profile like so:

```
[vagrant@freebsd-compile ~]$ diff -u .profile.bak .profile
--- .profile.bak	2018-03-16 18:51:59.288037000 +0000
+++ .profile	2018-03-16 18:49:45.273190000 +0000
@@ -29,4 +29,4 @@
 export GOPATH=/opt/gopath
 export PATH=$GOPATH/bin:$PATH

-cd /opt/gopath/src/github.com/sean-/vpc
+cd /opt/gopath/src/github.com/joyent/freebsd-vpc
```

How would I go about doing that and getting a new image?

**Comment by jen20** [comment]
@trentm There are two parts to this - the bits built into the base box (i.e. `joyent/FreeBSD-12.0-CURRENT-VPC`) and bits brought in when `vagrant up` runs. Things like `.profile` are edited using the scripts in `scripts/vagrant` when various machines come up. Their ordering is defined in `Vagrantfile` in the root of the repository.

The base box is built using the Packer template in `vagrant/packer` (the `make vagrant-box` will invoke this). This requires an ISO of FreeBSD with an appropriate kernel built using the FreeBSD build process (`make buildworld; make buildkernel; cd release && make cdrom`). Right now the FreeBSD build is done manually whenever there are new commits of interest, and Packer is run locally from that ISO - that could be put under CI but will need a build agent which can run VMWare.
